# Generated by Django 6.0 on 2025-12-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Полное имя"),
                ),
                (
                    "comment",
                    models.CharField(max_length=100, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Получаель",
                "verbose_name_plural": "Получатели",
                "db_table": "recipients",
                "ordering": ["email"],
            },
        ),
    ]
