# Generated by Django 6.0 on 2025-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MailingApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
            ],
        ),
    ]
