# Generated by Django 6.0 on 2025-12-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MailingApp", "0002_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailrecipient",
            options={
                "ordering": ["email"],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["topic"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelTable(
            name="message",
            table="messages",
        ),
    ]
