# Generated by Django 6.0 on 2025-12-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "MailingApp",
            "0003_alter_mailrecipient_options_alter_message_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MailManage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создана"),
                            ("STARTED", "Запущена"),
                            ("ENDED", "Завершена"),
                        ],
                        default="CREATED",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mailing_manage",
                        to="MailingApp.message",
                    ),
                ),
                ("recipient", models.ManyToManyField(to="MailingApp.mailrecipient")),
            ],
            options={
                "verbose_name": "Пользователи и рассылки",
                "verbose_name_plural": "Пользователи и рассылки",
                "db_table": "mail_manage",
            },
        ),
    ]
