# Generated by Django 6.0 on 2025-12-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MailingApp", "0004_mailmanage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailmanage",
            options={
                "verbose_name": "Пользователи_и_рассылки",
                "verbose_name_plural": "Пользователи_и_рассылки",
            },
        ),
    ]
