# Generated by Django 6.0 on 2025-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MailingApp", "0005_alter_mailmanage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailmanage",
            options={
                "ordering": ["message"],
                "verbose_name": "Пользователи_и_рассылки",
                "verbose_name_plural": "Пользователи_и_рассылки",
            },
        ),
        migrations.AddField(
            model_name="mailmanage",
            name="date_first_send",
            field=models.DateField(
                null=True, verbose_name="Дата и время пераой отправки"
            ),
        ),
        migrations.AddField(
            model_name="mailmanage",
            name="date_last_send",
            field=models.DateField(
                null=True, verbose_name="Дата и время окончания отправки"
            ),
        ),
    ]
