# Generated by Django 6.0 on 2025-12-14 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "MailingApp",
            "0006_alter_mailmanage_options_mailmanage_date_first_send_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailmanage",
            name="date_first_send",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время пераой отправки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailmanage",
            name="date_last_send",
            field=models.DateField(
                auto_now_add=True,
                verbose_name="Дата и время окончания отправки",
            ),
            preserve_default=False,
        ),
    ]
